# One-time Azure setup for the przm-bench Azure OpenAI adapter.
#
# Creates:
#   1. Resource group `rg-przm` in $Region
#   2. Service principal `claude-code-przm` scoped to that RG only (Contributor)
#   3. SP credential stored in Windows Credential Manager via PowerShell
#      SecretManagement + SecretStore (DPAPI-encrypted to your user account)
#   4. $500/month budget alert on the RG with email notification at 80%
#
# Safe to re-run: skips steps already done. The SP secret is generated by
# Azure ONCE and visible briefly in memory inside this script. It never goes
# to stdout, the clipboard, or a file. The encrypted store survives reboots.
#
# What this script does NOT do:
#   - Provision any Azure OpenAI deployments (that's the next step, scripted)
#   - Grant the SP access to anything outside the resource group
#   - Create resources that incur cost beyond the empty RG itself
#
# Run from elevated PowerShell? No — current-user scope only.
# Prereqs: az CLI (https://aka.ms/installazurecliwindows), an authenticated
# `az login` session as a user with Owner/Contributor on the subscription
# (needed to create the SP role assignment).

[CmdletBinding()]
param(
    [string]$ResourceGroup = 'rg-przm',
    [string]$Region        = 'eastus2',
    [string]$SpName        = 'claude-code-przm',
    [string]$VaultName     = 'OneNomadPrzm',
    [string]$SecretName    = 'azure-sp-claude-code-przm',
    [int]   $BudgetUsd     = 500,
    [string]$AlertEmail    = 'hello@mattstvartak.com'
)

$ErrorActionPreference = 'Stop'

function Write-Step([string]$msg) {
    Write-Host "`n==> $msg" -ForegroundColor Cyan
}

# ── 0. Sanity ─────────────────────────────────────────────────────────────
Write-Step 'Sanity checks'

if (-not (Get-Command az -ErrorAction SilentlyContinue)) {
    throw 'Azure CLI not found. Install with: winget install Microsoft.AzureCLI'
}

$account = az account show --output json 2>$null | ConvertFrom-Json
if (-not $account) {
    throw 'Not logged in. Run `az login` first, then re-run this script.'
}

$subId = $account.id
$tenantId = $account.tenantId
Write-Host "  Subscription : $($account.name) ($subId)"
Write-Host "  Tenant       : $tenantId"
Write-Host "  Signed in as : $($account.user.name)"

# ── 1. Resource group ────────────────────────────────────────────────────
Write-Step "Resource group $ResourceGroup in $Region"

$rgExists = az group exists --name $ResourceGroup --output tsv
if ($rgExists -eq 'true') {
    Write-Host '  Already exists.'
} else {
    az group create --name $ResourceGroup --location $Region --output none
    Write-Host '  Created.'
}

# ── 2. Service principal ─────────────────────────────────────────────────
Write-Step "Service principal $SpName scoped to $ResourceGroup"

$scope = "/subscriptions/$subId/resourceGroups/$ResourceGroup"

# Check if SP already exists under this name. If so, regenerate the password
# (we can't read the existing one). If not, create fresh.
$existingSp = az ad sp list --display-name $SpName --output json | ConvertFrom-Json
if ($existingSp.Count -gt 0) {
    Write-Host "  SP exists (appId $($existingSp[0].appId)). Rotating password..."
    $appId = $existingSp[0].appId
    $newCred = az ad app credential reset --id $appId --append --output json | ConvertFrom-Json
    $spJson = [PSCustomObject]@{
        appId    = $appId
        password = $newCred.password
        tenant   = $tenantId
    }
    # Ensure scope assignment still exists
    az role assignment create `
        --assignee $appId `
        --role Contributor `
        --scope $scope `
        --output none 2>$null
} else {
    Write-Host '  Creating new SP with Contributor on RG only...'
    $spJson = az ad sp create-for-rbac `
        --name $SpName `
        --role Contributor `
        --scopes $scope `
        --output json | ConvertFrom-Json
}

# ── 3. Store the SP credential ──────────────────────────────────────────
Write-Step "Store credential in Windows Credential Manager"

# Install / verify SecretManagement + SecretStore
foreach ($mod in @('Microsoft.PowerShell.SecretManagement', 'Microsoft.PowerShell.SecretStore')) {
    if (-not (Get-Module -ListAvailable -Name $mod)) {
        Write-Host "  Installing $mod (CurrentUser scope)..."
        Install-Module -Name $mod -Scope CurrentUser -Force -AllowClobber | Out-Null
    }
}
Import-Module Microsoft.PowerShell.SecretManagement
Import-Module Microsoft.PowerShell.SecretStore

# Configure SecretStore for no-prompt access BEFORE any read.
# (DPAPI-encrypted to current user; any process running as you can read it.)
# NOTE: Do NOT call Get-SecretStoreConfiguration first — on an
# uninitialized store, that triggers the master-password prompt itself.
# Just call Set-, which is idempotent and works on fresh stores too.
Write-Host '  Configuring SecretStore: no master-password prompt.'
Set-SecretStoreConfiguration -Authentication None -Interaction None -Confirm:$false

# Register the vault if not already
if (-not (Get-SecretVault -Name $VaultName -ErrorAction SilentlyContinue)) {
    Register-SecretVault -Name $VaultName -ModuleName Microsoft.PowerShell.SecretStore -DefaultVault | Out-Null
}

# Store the SP JSON as one secret blob
$secretPayload = @{
    appId          = $spJson.appId
    password       = $spJson.password
    tenant         = $spJson.tenant
    subscriptionId = $subId
    resourceGroup  = $ResourceGroup
    region         = $Region
} | ConvertTo-Json -Compress

Set-Secret -Vault $VaultName -Name $SecretName -Secret $secretPayload
Write-Host "  Stored as $VaultName / $SecretName."

# ── 4. Budget alert ──────────────────────────────────────────────────────
Write-Step "Budget alert: \$$BudgetUsd/month on $ResourceGroup"

$startDate = (Get-Date -Format 'yyyy-MM-01')
$endDate   = (Get-Date).AddYears(2).ToString('yyyy-MM-01')

$budgetJson = @{
    properties = @{
        category      = 'Cost'
        amount        = $BudgetUsd
        timeGrain     = 'Monthly'
        timePeriod    = @{ startDate = $startDate; endDate = $endDate }
        notifications = @{
            'alert-80-percent' = @{
                enabled        = $true
                operator       = 'GreaterThan'
                threshold      = 80
                contactEmails  = @($AlertEmail)
                notificationLanguage = 'en-us'
                thresholdType  = 'Actual'
            }
            'alert-100-percent' = @{
                enabled        = $true
                operator       = 'GreaterThan'
                threshold      = 100
                contactEmails  = @($AlertEmail)
                notificationLanguage = 'en-us'
                thresholdType  = 'Actual'
            }
        }
    }
} | ConvertTo-Json -Depth 6

$tmpFile = [System.IO.Path]::GetTempFileName()
Set-Content -Path $tmpFile -Value $budgetJson -Encoding UTF8
try {
    az rest --method PUT `
        --uri "https://management.azure.com/subscriptions/$subId/resourceGroups/$ResourceGroup/providers/Microsoft.Consumption/budgets/budget-przm-$BudgetUsd`?api-version=2023-11-01" `
        --body "@$tmpFile" `
        --output none 2>&1 | Out-Null
    Write-Host "  Budget alert configured (80% and 100% thresholds → $AlertEmail)."
} catch {
    Write-Warning "  Budget alert creation failed. Create manually in Portal: Cost Management → Budgets → $ResourceGroup."
} finally {
    Remove-Item $tmpFile -Force -ErrorAction SilentlyContinue
}

# ── 5. Output for the agent ──────────────────────────────────────────────
Write-Step 'Done. Share these (NON-SECRET) values with the agent'

Write-Host ''
$publicInfo = [PSCustomObject]@{
    appId          = $spJson.appId
    tenantId       = $tenantId
    subscriptionId = $subId
    resourceGroup  = $ResourceGroup
    region         = $Region
    vaultName      = $VaultName
    secretName     = $SecretName
}
$publicInfo | Format-List
$publicInfo | ConvertTo-Json -Compress

Write-Host ''
Write-Host 'The SP password is NOT printed. It lives in Windows Credential Manager only.' -ForegroundColor Yellow
Write-Host 'To verify retrieval works:' -ForegroundColor Yellow
Write-Host "  Get-Secret -Vault $VaultName -Name $SecretName -AsPlainText | ConvertFrom-Json" -ForegroundColor DarkGray
